os: linux
dist: xenial
language: python
services:
  - docker
  - mongodb
  - xvfb

env:
  global:
    - MPLBACKEND: Qt5Agg

cache:
  directories:
    - $HOME/.cache/pip
    - $HOME/.ccache  # https://github.com/travis-ci/travis-ci/issues/5853

jobs:
  fast_finish: true
  include:
    - os: linux
      python: 3.6
    - os: linux
      python: 3.7
    - os: linux
      python: 3.8
    - os: linux
      python: 3.6
      env:
        - USE_DOCKER: true

install:
  # Install this package and the packages listed in requirements.txt.
  - pip install .
  # Install extra requirements for running tests and building docs.
  - pip install -r requirements-dev.txt
  - pip install --upgrade numpy pip
  - pip list
  - mkdir -p $HOME/.config/databroker/ && cp -v examples/local.yml $HOME/.config/databroker/local.yml
  - |
    if [ ! -z "$USE_DOCKER" ]; then
        docker pull radiasoft/sirepo:beta
        mkdir -v -p $HOME/sirepo_srdb_root
        cp -Rv sirepo_bluesky/tests/SIREPO_SRDB_ROOT $HOME/sirepo_srdb_root
    fi

script:
  - flake8  # Enforce code style ('relaxed' line length limit is set in .flake8 config file).
  - |
    if [ ! -z "$USE_DOCKER" ]; then
        docker run -d -t --rm -e SIREPO_AUTH_METHODS=bluesky:guest -e SIREPO_AUTH_BLUESKY_SECRET=bluesky -e SIREPO_SRDB_ROOT=/sirepo -e SIREPO_COOKIE_IS_SECURE=false -p 8000:8000 -v $HOME/sirepo_srdb_root:/sirepo:rw,z radiasoft/sirepo:beta /home/vagrant/.pyenv/shims/sirepo service http
        coverage run -m pytest -vvvv -m "docker"  # Run the tests and check for test coverage.
    fi
  - coverage run -m pytest -vvvv -m "not docker"  # Run the tests and check for test coverage.
  - coverage report -m  # Generate test coverage report.
  - codecov  # Upload the report to codecov.
  - make -C docs html  # Build the documentation.
